{% set name = "jupyterlab-js" %}
{% set version = "4.4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e8e184079f125824be6c12e1ea2556e01903d8b69f2008f99db1dd6139aa8e0a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - hatchling
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - jupyterlab_js
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/davidbrochart/jupyterlab-js
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package distributing JupyterLab's static assets
  dev_url: https://github.com/davidbrochart/jupyterlab-js

extra:
  recipe-maintainers:
    - davidbrochart
